name: base-test #название теста

on: #когда тест запускается 
  - push
  - pull_request

jobs: #тут начинается работа 
  build-base: #название  
    runs-on: ubuntu-latest #штука, типа платформы для работы экшена
    
    steps: #шаги 
      - uses: actions/checkout@v3 #клонирует репозиторий
      - uses: actions/setup-node@v3 #устанавливает node.js - прога, которая работает с js
        with: 
          node-version: '16' #условие, что устанавливать надо версию 16
          cache: 'npm' #тут происходит кэш для менеджера пакетов node.js

      #- run: npm install @react-navigation/native @react-navigation/native-stack --force 
      
      #- run: npm i expo-doctor
      #- run: expo doctor
      #- run: expo doctor --fix-dependencies
          
      #- run: npm i react-router-dom@^5.1.2
      #- run: npm install react react-dom
      #- run: npm i styled-components@^5.2.0
      #- run: npm install superagent
     #- run: npm audit fix --force
       
      - run: make setup #команда из Makefile, устанавливает и собирает nmp
      - run: make test #тестирует nmp
      - run: make lint #действо с eslint, не до конца поняла, что именно оно делает
  
  build-shyk:
    if: ${{ always() }} 
    needs: build-base #выполнение тестирования с помощью shyk, после выполнения предыдущей команды "build-base"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master #клонирование репозитория, если не ошибаюсь. 
        #Не до конца понимаю, что означает master (это версия?). И вопрос, нужно ли опять копировать репозиторий?
      - uses: snyk/actions/node@master #тут запускается экшен от shyk
        continue-on-error: true #строка, которая не выдает ошибку, если тесты выдали уязвимости
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} #тут секрутная штука, типа ключа, чтобы сконектиться с shyk
